// The TextMate grammar's inner syntax (syntaxes/isabelle-grammar.json, generated by
// scripts/gen_grammar.scala). Pure -- tokenised with vscode-textmate, the library VS Code
// itself uses, so no editor and no prover.
//
// What is held down: a term in "..." or a cartouche is inner syntax, not one string, so
// its parts can be told apart before PIDE has checked it; the places where quotes and
// cartouches are *not* terms (prose, ML, file names, the theory header) keep their old
// meaning; and inner syntax never picks up an outer keyword rule (`case`, `let`, `in` are
// both).
const assert = require('assert')
const fs = require('fs')
const path = require('path')
const vsctm = require('vscode-textmate')
const oniguruma = require('vscode-oniguruma')

let passed = 0
const pass = m => { passed++; console.log('PASS: ' + m) }

const GRAMMAR = path.join(__dirname, '..', 'syntaxes', 'isabelle-grammar.json')

async function loadGrammar() {
  await oniguruma.loadWASM(fs.readFileSync(require.resolve('vscode-oniguruma/release/onig.wasm')))
  const registry = new vsctm.Registry({
    onigLib: Promise.resolve({
      createOnigScanner: patterns => new oniguruma.OnigScanner(patterns),
      createOnigString: s => new oniguruma.OnigString(s),
    }),
    loadGrammar: async scope => scope === 'source.isabelle'
      ? vsctm.parseRawGrammar(fs.readFileSync(GRAMMAR, 'utf8'), GRAMMAR)
      : null,
  })
  return registry.loadGrammar('source.isabelle')
}

/** Tokenise a whole text; returns [{ line, start, end, text, scopes }]. */
function tokenize(grammar, text) {
  const out = []
  let stack = vsctm.INITIAL
  text.split('\n').forEach((line, i) => {
    const r = grammar.tokenizeLine(line, stack)
    for (const t of r.tokens) {
      out.push({ line: i, start: t.startIndex, end: t.endIndex,
                 text: line.slice(t.startIndex, t.endIndex), scopes: t.scopes })
    }
    stack = r.ruleStack
  })
  return out
}

/** Scopes of the token holding the first character of the nth occurrence of `needle`. */
function scopesAt(tokens, text, needle, nth = 0) {
  let at = -1
  for (let k = 0; k <= nth; k++) {
    at = text.indexOf(needle, at + 1)
    assert.ok(at >= 0, `${JSON.stringify(needle)} #${nth} not in ${JSON.stringify(text)}`)
  }
  const before = text.slice(0, at).split('\n')
  const line = before.length - 1
  const char = before[before.length - 1].length
  const token = tokens.find(t => t.line === line && t.start <= char && char < t.end)
  assert.ok(token, `no token at ${JSON.stringify(needle)}`)
  return token.scopes
}

function check(grammar, text) {
  const tokens = tokenize(grammar, text)
  const at = (needle, nth) => scopesAt(tokens, text, needle, nth)
  const has = (needle, scope, nth) => {
    const s = at(needle, nth)
    assert.ok(s.some(x => x.split(' ').some(y => y === scope || y.startsWith(scope + '.'))),
      `${JSON.stringify(needle)} in ${JSON.stringify(text)} should have ${scope}, has ${s.join(' / ')}`)
  }
  const lacks = (needle, scope, nth) => {
    const s = at(needle, nth)
    assert.ok(!s.some(x => x.split(' ').some(y => y === scope || y.startsWith(scope + '.'))),
      `${JSON.stringify(needle)} in ${JSON.stringify(text)} should not have ${scope}, has ${s.join(' / ')}`)
  }
  /** Plain inside a term: no scope below meta.term, in particular not a string. */
  const plain = (needle, nth) => {
    const s = at(needle, nth)
    assert.strictEqual(s[s.length - 1], 'meta.term.isabelle',
      `${JSON.stringify(needle)} in ${JSON.stringify(text)} should be plain term text, has ${s.join(' / ')}`)
  }
  /**
   * A quote or cartouche bracket that keeps the string colour. A theme styles a token by
   * its innermost scope, and gives string delimiters their colour through
   * punctuation.definition.string -- any other punctuation.* innermost falls to a plain
   * `punctuation` rule, which in Breeze Dark is the keyword blue.
   */
  const stringDelimiter = (needle, nth) => {
    const s = at(needle, nth)
    assert.ok(s[s.length - 1].startsWith('punctuation.definition.string.') &&
      s.some(x => x.startsWith('string.')),
      `${JSON.stringify(needle)} in ${JSON.stringify(text)} should be a string delimiter, has ${s.join(' / ')}`)
  }
  return { has, lacks, plain, stringDelimiter }
}

async function run() {
  const grammar = await loadGrammar()

  // --- the complaint: a term was one colour -------------------------------------------
  {
    const t = check(grammar, 'lemma "map f (x # xs) = f x # map f xs"')
    t.plain('map'); t.plain('xs')
    t.lacks('map', 'string')
    t.has('#', 'keyword.operator.inner')
    t.has('=', 'keyword.operator.inner')
    t.stringDelimiter('"', 0)
    t.stringDelimiter('"', 1)
    t.has('lemma', 'keyword.control.isabelle')
  }
  pass('a quoted term is inner syntax: names plain, operators apart, only the quotes string-coloured')

  // --- inner words are not outer keywords ---------------------------------------------
  {
    const t = check(grammar, 'lemma "case x of None \\<Rightarrow> 0 | Some y \\<Rightarrow> y"')
    t.has('case', 'keyword.other.inner')
    t.lacks('case', 'entity.name.type')
    t.has('of', 'keyword.other.inner')
    t.has('\\<Rightarrow>', 'keyword.operator.inner')
    t.has('0', 'constant.numeric.inner')
    t.plain('None')
  }
  {
    const t = check(grammar, 'lemma "let y = 1 in y \\<in> index"')
    t.has('let', 'keyword.other.inner')
    t.lacks('let', 'keyword.control')
    t.has('in', 'keyword.other.inner')
    t.plain('index')
  }
  pass('case, let and in are inner keywords inside a term, never the outer ones; no match inside a name')

  // --- variables, types, symbols ------------------------------------------------------
  {
    const t = check(grammar, 'lemma "(x::\'a list) = ?y \\<and> P ?x.1 \\<and> \\<alpha> = x\'a \\<and> s = \'\'abc\'\'"')
    t.has('::', 'keyword.operator.type.inner')
    t.has("'a", 'entity.name.type.parameter')
    t.has('?y', 'variable.language.schematic')
    t.has('?x.1', 'variable.language.schematic')
    t.has('\\<and>', 'keyword.operator.inner')
    t.plain('\\<alpha>')
    t.plain("x'a")
    t.has("''abc''", 'string.quoted.single.inner')
  }
  {
    const t = check(grammar, 'lemma "\\<forall>x\\<^sub>1. (*) 2 x\\<^sub>1 = x (* note *) + 1.5"')
    t.has('\\<forall>', 'keyword.operator.inner')
    t.plain('x\\<^sub>1')
    t.has('(*)', 'keyword.operator.inner')
    t.has('(* note', 'comment.block')
    t.has('1.5', 'constant.numeric.inner')
  }
  pass("'a, ?x, ::, symbols, numerals, ''strings'' and comments; \\<alpha> and x\\<^sub>1 are names; (*) is not a comment")

  // --- cartouches ---------------------------------------------------------------------
  {
    const t = check(grammar, 'lemma \\<open>x = STR \\<open>s\\<close>\\<close>\nlemma ‹y ∧ z›')
    t.plain('x')
    t.has('=', 'keyword.operator.inner')
    t.has('s', 'string.quoted.other.inner')
    t.plain('y')
    t.has('∧', 'keyword.operator.inner')
    t.stringDelimiter('\\<open>', 0)
    t.stringDelimiter('\\<close>', 1)
  }
  pass('a cartouche in term position is inner syntax, in ASCII or glyphs; a nested one is a string')

  // --- where quotes and cartouches are not terms --------------------------------------
  {
    const t = check(grammar,
      'text \\<open>if 1 then\\<close>\nsection "Title with if"\n' +
      'lemma "x" \\<comment> \\<open>note if\\<close>\nML \\<open>val x = if 1 then 2 else 3\\<close>\n' +
      'txt ‹also prose›')
    t.has('if', 'string.quoted.other.multiline', 0)
    t.lacks('if', 'meta.term', 0)
    t.has('if', 'string.quoted.double.isabelle', 1)
    t.lacks('if', 'keyword.other.inner', 1)
    t.has('note', 'comment.block.marker')
    t.has('val', 'meta.embedded.block.ml')
    t.stringDelimiter('\\<open>', 2)
    t.lacks('if', 'keyword.other.inner', 3)
    t.has('also', 'string.quoted.other.multiline')
    t.has('text', 'keyword.control.isabelle')
    t.has('ML', 'keyword.control.isabelle')
  }
  {
    const t = check(grammar,
      'theory T\n  imports "HOL-Library.Multiset" Main\nbegin\nML_file "a.ML"\nexternal_file \\<open>b.txt\\<close>')
    t.has('HOL', 'string.quoted.double.isabelle')
    t.lacks('-', 'keyword.operator.inner')
    t.has('begin', 'keyword.other.unit.isabelle')
    t.has('a.ML', 'string.quoted.double.isabelle')
    t.has('b.txt', 'string.quoted.other.multiline')
  }
  pass('prose, \\<comment>, ML, file names and the theory header keep their meaning')

  // --- regions end where they should --------------------------------------------------
  {
    const t = check(grammar,
      'text \\<open>a\\<close>\nlemma "if b then c else d"\ntext\nlemma \\<open>let x = y in x\\<close>\n' +
      'method_setup m = \\<open>Scan.succeed\\<close> "descr"\nlemma "zzz"')
    t.has('if', 'keyword.other.inner')
    t.has('let', 'keyword.other.inner')
    t.has('Scan', 'meta.embedded.block.ml')
    t.plain('zzz')
  }
  {
    const t = check(grammar, 'lemma "x =\n    y + 1"\nlemma "a \\"b\\" c"')
    t.has('+', 'keyword.operator.inner')
    t.plain('y')
    t.has('\\"', 'constant.character.escape')
    t.plain('c')
  }
  pass('a command region ends after its cartouche or at the next command; terms span lines')

  console.log(passed + ' checks passed')
  console.log('SUITE38_OK')
}

module.exports = { run }

if (require.main === module) {
  run().catch(err => { console.error(err); process.exit(1) })
}
